import type { PlayerProfile } from "@/types/tarkov";
import {
  getPlayerLevels,
  getPublicProfile,
  parseArenaProfileStats,
  parseProfileStats,
  pveProfileDecision,
} from "@/lib/tarkov-api";
export {
  PVE_SKILL_CUTOFF_SECONDS,
  pveProfileDecision,
  type PveProfileDecision,
} from "@/lib/tarkov-api";
import { getStore } from "@/lib/db";
import { makePlayerSnapshot, type PlayerSnapshotInput } from "@/lib/ban-db";
import { isGameMode } from "@/types/seasonal";
import type { CrossSectionMode } from "@/lib/db";

export interface OperatorProfilePayload {
  aid: number;
  profile: PlayerProfile;
  mode: CrossSectionMode;
}

export type TrackedProfileResolution =
  | { state: "profile"; payload: OperatorProfilePayload }
  | { state: "not_found" }
  | { state: "invalid" };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function parseOperatorProfilePayload(value: unknown): OperatorProfilePayload | null {
  if (!isRecord(value)) return null;
  const aid = Number(value.aid);
  const profile = value.profile;
  const mode = value.mode ?? "regular";
  if (!isGameMode(mode) || mode === "seasonal") return null;
  if (!Number.isSafeInteger(aid) || aid <= 0 || !isRecord(profile)) return null;
  if (Number(profile.aid) !== aid || !isRecord(profile.info)) return null;
  return { aid, profile: profile as unknown as PlayerProfile, mode };
}

export function parseOperatorAid(value: unknown): number | null {
  if (!isRecord(value)) return null;
  const aid = Number(value.aid);
  return Number.isSafeInteger(aid) && aid > 0 ? aid : null;
}

/**
 * Accepts the legacy full-profile payload as well as the extension's compact
 * `{ aid }` payload. In the latter case the browser has already completed the
 * interactive refresh, so bypass our in-process cache and read the fresh
 * public profile generated by tarkov.dev.
 */
export async function resolveOperatorProfilePayload(
  value: unknown
): Promise<OperatorProfilePayload | null> {
  const embedded = parseOperatorProfilePayload(value);
  if (embedded) return embedded;

  const aid = parseOperatorAid(value);
  if (aid === null) return null;

  const { profile } = await getPublicProfile(aid, { force: true });
  const resolved = profile ? parseOperatorProfilePayload({ aid, profile, mode: "regular" }) : null;
  if (!resolved) {
    throw new Error("refreshed public profile is unavailable");
  }
  return resolved;
}

/** Server-only refresh for a version observed in profile/updated.json. */
export async function resolveTrackedProfilePayload(value: unknown): Promise<TrackedProfileResolution> {
  if (!isRecord(value)) return { state: "invalid" };
  const aid = Number(value.aid);
  const expectedUpdatedAt = Number(value.expectedUpdatedAt);
  const mode = value.mode ?? "regular";
  if (
    (mode !== "regular" && mode !== "pve" && mode !== "arena") ||
    !Number.isSafeInteger(aid) || aid <= 0 ||
    !Number.isSafeInteger(expectedUpdatedAt) || expectedUpdatedAt <= 0
  ) {
    return { state: "invalid" };
  }

  const { profile } = await getPublicProfile(aid, { force: true, mode, expectedUpdatedAt });
  if (!profile) return { state: "not_found" };
  const payload = parseOperatorProfilePayload({ aid, profile, mode });
  if (!payload) throw new Error("tracked public profile is invalid");
  return { state: "profile", payload };
}

function normalizedUpdatedAt(profile: PlayerProfile, required = false): number {
  const value = Number(profile.updated);
  if (!Number.isFinite(value) || value <= 0) {
    if (required) throw new Error("regular profile.updated must be a positive timestamp");
    return Date.now();
  }
  // Accept seconds defensively even though the current payload uses Unix ms.
  return value < 1_000_000_000_000 ? Math.round(value * 1000) : Math.round(value);
}

export async function snapshotFromOperatorProfile(
  payload: OperatorProfilePayload,
  options: { upsertPlayer?: boolean } = {}
): Promise<PlayerSnapshotInput> {
  const updatedAt = normalizedUpdatedAt(payload.profile, payload.mode === "regular");
  const levels = payload.mode === "arena" ? [] : await getPlayerLevels().catch(() => []);
  const stats = payload.mode === "arena"
    ? parseArenaProfileStats(payload.profile)
    : parseProfileStats(payload.profile, levels);
  const achievementIds = payload.profile.achievements
    ? Object.keys(payload.profile.achievements)
    : [];

  const shouldStore = payload.mode !== "pve" || pveProfileDecision(payload.profile).state === "store";
  if (options.upsertPlayer !== false && shouldStore) {
    const store = await getStore(payload.mode);
    if (!store) throw new Error("player store unavailable");
    await store.upsert(payload.aid, stats, achievementIds);
  }

  return makePlayerSnapshot(
    payload.aid,
    stats,
    achievementIds,
    updatedAt
  );
}
